import { ipaEntries, consonantManners, consonantPlaces, references } from './data/ipa-data.js';
import { searchIPA, relatedFor } from './domain/search.js';
import { dueEntries, gradeReview, grades, progressStats } from './domain/srs.js';
import { defaultState, emptyReview, exportState, loadState, saveState } from './services/storage.js';
import { languages, t } from './i18n/translations.js';

const app = document.querySelector('#app');
let state = loadState();
let route = 'home';
let activeCategory = 'pulmonic-consonant';
let selected = null;
let practiceEntry = ipaEntries[0];
let flashcardRevealed = false;
let keyboardText = '';

function setState(next) { state = typeof next === 'function' ? next(state) : next; saveState(state); applyPreferences(); render(); }
function openEntry(entry) { selected = entry; state = { ...state, recent: [entry.id, ...state.recent.filter((id) => id !== entry.id)].slice(0, 10) }; saveState(state); render(); }
function closeEntry() { selected = null; render(); }
function navigate(next) { route = next; render(); }
function lang() { return state.language in languages ? state.language : 'en'; }
function escapeHtml(text = '') { return String(text).replace(/[&<>"]/g, (m) => ({ '&':'&amp;', '<':'&lt;', '>':'&gt;', '"':'&quot;' }[m])); }
function button(label, attrs = '') { return `<button ${attrs}>${label}</button>`; }
function icon(name) { return ({ home:'⌂', chart:'ɑ', learn:'◫', practice:'✓', progress:'◉', search:'⌕', settings:'⚙' })[name] || '•'; }
function entryLabel(entry) { return entry.names[lang()]?.description || entry.names.en.description; }
function entryCard(entry) { return `<button class="symbol-card" data-open="${entry.id}" aria-label="${escapeHtml(entryLabel(entry))}, IPA symbol ${escapeHtml(entry.symbol)}"><strong lang="en-fonipa">${escapeHtml(entry.symbol)}</strong><span>${escapeHtml(entryLabel(entry))}</span><small>${escapeHtml([entry.placeOfArticulation, entry.mannerOfArticulation, entry.vowelHeight, entry.vowelBackness, entry.rounded === true ? 'rounded' : entry.rounded === false ? 'unrounded' : ''].filter(Boolean).join(' · '))}</small></button>`; }
function header(title, subtitle) { return `<header class="top"><p class="eyebrow">IPA Learner</p><h1>${escapeHtml(title)}</h1><p>${escapeHtml(subtitle)}</p></header>`; }
function applyPreferences() { document.documentElement.lang = lang(); document.documentElement.dataset.theme = state.theme; document.documentElement.classList.toggle('large-text', state.largeText); document.documentElement.classList.toggle('high-contrast', state.highContrast); document.documentElement.classList.toggle('reduce-motion', state.reducedMotion); }
function homeView(stats) { const recent = state.recent.map((id) => ipaEntries.find((entry) => entry.id === id)).filter(Boolean); const weak = dueEntries(ipaEntries, state.review).slice(0, 5); return `${header('Good evening', 'Your short daily IPA session is ready for one-handed study.')}
<section class="hero-card"><div><h2>${t(lang(),'continue')}</h2><p>Today: review 3 symbols, learn 2 new sounds, answer 5 questions.</p></div>${button('Start 5-minute session','data-nav="practice" class="primary"')}</section>
<section class="metrics"><article><b>${stats.mastery}%</b><span>${t(lang(),'mastery')}</span></article><article><b>${stats.due}</b><span>Due today</span></article><article><b>${state.streak}</b><span>${t(lang(),'streak')}</span></article></section>
<section class="quick-actions">${button(t(lang(),'daily'),'data-nav="practice"')}${button(t(lang(),'chart'),'data-nav="chart"')}${button(t(lang(),'search'),'data-nav="search"')}${button(t(lang(),'review'),'data-nav="practice"')}</section>
<h2>${t(lang(),'weak')}</h2><div class="cards compact">${weak.map(entryCard).join('')}</div>
<h2>Recent symbols</h2><div class="cards compact">${(recent.length ? recent : ipaEntries.slice(0, 6)).map(entryCard).join('')}</div>`; }
function chartView() { const categories = ['pulmonic-consonant','vowel','non-pulmonic-consonant','diacritic','suprasegmental','tone']; const entries = ipaEntries.filter((entry) => entry.category === activeCategory); return `${header(t(lang(),'chart'), 'Browse a structured, interactive IPA chart without squeezing a desktop table onto a phone.')}
<div class="segmented" role="tablist">${categories.map((cat) => button(cat.replaceAll('-', ' '), `data-category="${cat}" class="${activeCategory === cat ? 'active' : ''}" role="tab" aria-selected="${activeCategory === cat}"`)).join('')}</div>
${activeCategory === 'pulmonic-consonant' ? consonantGrid() : ''}${activeCategory === 'vowel' ? vowelChart() : ''}${activeCategory === 'diacritic' ? '<p class="notice">Diacritics modify base symbols. The dotted circle marks where the base symbol sits.</p>' : ''}
<div class="cards">${entries.map(entryCard).join('')}</div>`; }
function consonantGrid() { return `<section class="consonant-grid" aria-label="Pulmonic consonants by place and manner">${consonantPlaces.map((place) => `<article><h3>${place}</h3>${consonantManners.map((manner) => { const matches = ipaEntries.filter((entry) => entry.placeOfArticulation === place && entry.mannerOfArticulation === manner); return `<div class="chart-row"><span>${manner}</span><div>${matches.length ? matches.map((entry) => button(entry.symbol, `data-open="${entry.id}" aria-label="${entryLabel(entry)}"`)).join('') : '<em aria-label="No standard IPA symbol in this cell">—</em>'}</div></div>`; }).join('')}</article>`).join('')}</section>`; }
function vowelChart() { const xMap = { front:70, central:165, back:255 }; const yMap = { close:35, 'near-close':60, 'close-mid':90, mid:118, 'open-mid':148, 'near-open':172, open:195 }; const vowels = ipaEntries.filter((entry) => entry.category === 'vowel'); return `<section class="vowel-card"><svg viewBox="0 0 330 230" role="img" aria-label="Interactive vowel quadrilateral"><polygon points="60,22 285,35 238,202 95,202" /><text x="55" y="18">front</text><text x="150" y="24">central</text><text x="255" y="30">back</text>${vowels.map((entry) => { const x = xMap[entry.vowelBackness] + (entry.rounded ? 15 : -13); const y = yMap[entry.vowelHeight]; return `<g tabindex="0" role="button" data-open="${entry.id}" aria-label="${entryLabel(entry)}"><circle cx="${x}" cy="${y}" r="18"/><text x="${x}" y="${y + 7}" text-anchor="middle">${entry.symbol}</text></g>`; }).join('')}</svg><p>Pairs are shown with unrounded vowels left and rounded vowels right where both are present.</p></section>`; }
function learnView() { const lessons = ['IPA foundations and Unicode', 'Common consonants', 'Places of articulation', 'Manners of articulation', 'Core vowels', 'Voicing and airstreams', 'Diacritics', 'Suprasegmentals and tone', 'Difficult contrasts', 'Full IPA mastery']; return `${header(t(lang(),'learn'), 'Guided learning cards keep sessions short and adaptive.')}${lessons.map((lesson, index) => `<section class="lesson-card"><div><small>Level ${index + 1}</small><h2>${lesson}</h2><p>${index < 3 ? 'Recommended now' : 'Available as reference; practice will prioritize it when you are ready.'}</p></div><div class="cards compact">${ipaEntries.slice(index * 5, index * 5 + 5).map(entryCard).join('')}</div></section>`).join('')}`; }
function practiceView() { const review = state.review[practiceEntry.id] || emptyReview(); return `${header(t(lang(),'practice'), 'Flashcards, recognition, sound-to-symbol, classification, and spaced review modes share one progress model.')}
<section class="practice-card"><p class="eyebrow">${t(lang(),'flashcards')} · ${practiceEntry.category}</p><button class="flash-face" data-flip="true"><strong>${flashcardRevealed ? entryLabel(practiceEntry) : practiceEntry.symbol}</strong><span>${flashcardRevealed ? practiceEntry.howToProduce : 'Tap to reveal the description and production cue.'}</span></button><div class="inline-actions">${audioButton(practiceEntry)}${button('Open detail',`data-open="${practiceEntry.id}"`)}</div><div class="grades">${grades.map((grade) => button(grade, `data-grade="${grade}"`)).join('')}</div><p class="fine">Seen ${review.timesSeen} · mastery ${review.mastery}% · next review ${review.nextReview ? new Date(review.nextReview).toLocaleDateString() : 'after first grade'}</p></section>${quizPanel()}${keyboardPanel()}`; }
function quizPanel() { const choices = [practiceEntry, ...relatedFor(practiceEntry).slice(0, 3)].sort(() => Math.random() - 0.5); return `<section><h2>Four-choice recognition</h2><p>Which IPA symbol matches: <b>${entryLabel(practiceEntry)}</b>?</p><div class="choice-grid">${choices.map((entry) => button(`<span lang="en-fonipa">${entry.symbol}</span>`, `data-answer="${entry.id}" aria-label="Answer ${entry.symbol}"`)).join('')}</div><p id="quiz-feedback" class="notice" aria-live="polite"></p></section>`; }
function keyboardPanel() { const groups = ['pulmonic-consonant','vowel','diacritic','suprasegmental','tone']; return `<section><h2>${t(lang(),'keyboard')}</h2><textarea id="keyboard-text" aria-label="IPA transcription input">${escapeHtml(keyboardText)}</textarea>${groups.map((group) => `<details ${group === 'pulmonic-consonant' ? 'open' : ''}><summary>${group.replaceAll('-', ' ')}</summary><div class="keyboard-grid">${ipaEntries.filter((entry) => entry.category === group).slice(0, 70).map((entry) => button(entry.symbol, `data-key="${escapeHtml(entry.symbol)}" aria-label="Insert ${entryLabel(entry)}"`)).join('')}</div></details>`).join('')}<div class="inline-actions">${button(t(lang(),'copy'),'data-copy-keyboard="true"')}${button('⌫','data-backspace="true"')}${button('Clear','data-clear-keyboard="true"')}</div></section>`; }
function progressView(stats) { const byCategory = Object.groupBy ? Object.groupBy(ipaEntries, (entry) => entry.category) : ipaEntries.reduce((acc, entry) => ((acc[entry.category] ||= []).push(entry), acc), {}); return `${header(t(lang(),'progress'), 'Local-only learning analytics help prioritize weak areas without collecting personal data.')}
<section class="progress-hero"><div class="ring" style="--value:${stats.mastery}">${stats.mastery}%</div><div class="metrics vertical"><article><b>${stats.seen}</b><span>Symbols seen</span></article><article><b>${stats.accuracy}%</b><span>Quiz accuracy</span></article><article><b>${stats.difficult}</b><span>Marked difficult</span></article></div></section>
<section><h2>Category breakdown</h2>${Object.entries(byCategory).map(([cat, entries]) => { const seen = entries.filter((entry) => state.review[entry.id]).length; return `<div class="bar"><span>${cat.replaceAll('-', ' ')}</span><progress value="${seen}" max="${entries.length}"></progress><b>${seen}/${entries.length}</b></div>`; }).join('')}</section>`; }
function searchView() { const query = sessionStorage.getItem('ipa-query') || ''; const results = searchIPA(query); return `${header(t(lang(),'search'), 'Search by symbol, Unicode, English/Japanese/Hungarian names, articulation, voicing, examples, and common spellings.')}
<label class="search-box"><span>Search IPA</span><input id="search-input" value="${escapeHtml(query)}" autocomplete="off" inputmode="search" placeholder="ʃ, sh, alveolar, vowel…" /></label><div class="cards">${results.map(entryCard).join('')}</div>`; }
function settingsView() { return `${header(t(lang(),'settings'), 'Control language, appearance, accessibility, local data, references, and audio policy.')}
<section class="settings-list"><label>Language<select id="language-select">${Object.entries(languages).map(([code, name]) => `<option value="${code}" ${code === lang() ? 'selected' : ''}>${name}</option>`).join('')}</select></label><label>Appearance<select id="theme-select">${['system','light','dark'].map((theme) => `<option ${theme === state.theme ? 'selected' : ''}>${theme}</option>`).join('')}</select></label>${['largeText','highContrast','reducedMotion'].map((key) => `<label><input type="checkbox" data-setting="${key}" ${state[key] ? 'checked' : ''}/> ${key}</label>`).join('')}<label>Daily goal<input id="daily-goal" type="number" min="3" max="60" value="${state.dailyGoal}" /></label></section>
<section><h2>${t(lang(),'references')}</h2>${Object.values(references).map((ref) => `<p><a href="${ref.url}" rel="noreferrer">${ref.title}</a></p>`).join('')}<p class="notice">Audio policy: no external recording is bundled or played unless its record has verified source, creator, license, license URL, attribution, commercial-use, modification, and redistribution metadata.</p><div class="inline-actions">${button('Export progress','data-export="true"')}${button('Reset progress','data-reset="true"')}</div></section>`; }
function audioButton(entry) { return button(`🔊 ${t(lang(),'play')}`, `data-audio="${entry.id}" aria-label="${t(lang(),'play')}: ${entryLabel(entry)}"`); }
function detailSheet(entry) { const review = state.review[entry.id] || emptyReview(); const related = relatedFor(entry); return `<div class="sheet" role="dialog" aria-modal="true" aria-label="${entryLabel(entry)}"><article class="sheet-card"><button class="close" data-close="true" aria-label="Close">×</button><button class="detail-symbol" data-copy="${escapeHtml(entry.symbol)}" aria-label="${t(lang(),'copy')} ${entry.symbol}">${escapeHtml(entry.symbol)}</button><h2>${escapeHtml(entryLabel(entry))}</h2><div class="inline-actions">${audioButton(entry)}${button(review.favorite ? '★ ' + t(lang(),'favorite') : '☆ ' + t(lang(),'favorite'), 'data-toggle="favorite"')}${button(review.difficult ? '⚠ ' + t(lang(),'difficult') : '△ ' + t(lang(),'difficult'), 'data-toggle="difficult"')}</div><section><h3>${t(lang(),'classification')}</h3><div class="chips">${[entry.category, entry.voicing, entry.placeOfArticulation, entry.mannerOfArticulation, entry.vowelHeight, entry.vowelBackness, entry.rounded === true ? 'rounded' : entry.rounded === false ? 'unrounded' : ''].filter(Boolean).map((chip) => `<span>${escapeHtml(chip)}</span>`).join('')}</div></section><section><h3>Names</h3><p><b>English:</b> ${entry.names.en.name}</p><p><b>日本語:</b> ${entry.names.ja.name}</p><p><b>Magyar:</b> ${entry.names.hu.name}</p></section><section><h3>${t(lang(),'produce')}</h3><p>${escapeHtml(entry.howToProduce)}</p></section><section><h3>Similar sounds</h3><div class="cards compact">${related.map(entryCard).join('')}</div></section><section><h3>${t(lang(),'notes')}</h3><textarea id="note-input" aria-label="${t(lang(),'notes')}">${escapeHtml(review.notes)}</textarea></section><section><h3>Audio licensing</h3>${entry.audioSources.map((src) => `<p class="fine"><b>${src.creator}</b>: ${src.license}. ${src.notes} <a href="${src.url}">Source</a></p>`).join('')}</section></article></div>`; }
function onboarding() { return `<main class="onboarding">${header('Welcome to IPA Learner', 'Set a starting point or skip; all data stays on this device.')}<section><label>Goal<select id="goal"><option>Learn IPA from scratch</option><option>Improve IPA transcription</option><option>Study linguistics</option><option>Improve pronunciation knowledge</option><option>Review IPA</option></select></label><label>Interface language<select id="onboard-lang">${Object.entries(languages).map(([code, name]) => `<option value="${code}">${name}</option>`).join('')}</select></label><label>Experience<select id="level"><option>Complete beginner</option><option>Some IPA knowledge</option><option>Intermediate</option><option>Advanced</option></select></label><div class="inline-actions">${button('Start','data-finish-onboarding="true" class="primary"')}${button('Skip','data-skip-onboarding="true"')}</div></section></main>`; }
function render() { applyPreferences(); const stats = progressStats(ipaEntries, state.review); const views = { home:homeView, chart:chartView, learn:learnView, practice:practiceView, progress:() => progressView(stats), search:searchView, settings:settingsView }; app.innerHTML = `${state.onboarded ? `<main>${views[route](stats)}</main><nav aria-label="Primary navigation">${['home','chart','learn','practice','progress','search','settings'].map((item) => button(`<span>${icon(item)}</span><small>${t(lang(), item)}</small>`, `data-nav="${item}" class="${route === item ? 'active' : ''}" aria-current="${route === item ? 'page' : 'false'}"`)).join('')}</nav>${selected ? detailSheet(selected) : ''}` : onboarding()}`; }
function chooseNextPractice() { const due = dueEntries(ipaEntries, state.review); practiceEntry = due[Math.floor(Math.random() * Math.min(due.length, 24))] || ipaEntries[0]; flashcardRevealed = false; }
app.addEventListener('input', (event) => { if (event.target.id === 'search-input') { sessionStorage.setItem('ipa-query', event.target.value); render(); } if (event.target.id === 'keyboard-text') keyboardText = event.target.value; if (event.target.id === 'note-input' && selected) setState((old) => ({ ...old, review:{ ...old.review, [selected.id]:{ ...(old.review[selected.id] || emptyReview()), notes:event.target.value } } })); });
app.addEventListener('change', (event) => { if (event.target.id === 'language-select') setState({ ...state, language:event.target.value }); if (event.target.id === 'theme-select') setState({ ...state, theme:event.target.value }); if (event.target.id === 'daily-goal') setState({ ...state, dailyGoal:Number(event.target.value) }); if (event.target.dataset.setting) setState({ ...state, [event.target.dataset.setting]:event.target.checked }); });
app.addEventListener('click', async (event) => { const target = event.target.closest('button,[data-open],g'); if (!target) return; const openId = target.dataset.open; if (openId) openEntry(ipaEntries.find((entry) => entry.id === openId)); if (target.dataset.nav) navigate(target.dataset.nav); if (target.dataset.category) { activeCategory = target.dataset.category; render(); } if (target.dataset.close) closeEntry(); if (target.dataset.flip) { flashcardRevealed = !flashcardRevealed; render(); } if (target.dataset.grade) { setState((old) => ({ ...old, review:{ ...old.review, [practiceEntry.id]:gradeReview(old.review[practiceEntry.id], target.dataset.grade) } })); chooseNextPractice(); } if (target.dataset.answer) { const correct = target.dataset.answer === practiceEntry.id; document.querySelector('#quiz-feedback').textContent = correct ? 'Correct — now grade your confidence.' : `Not quite. Correct answer: ${practiceEntry.symbol} (${entryLabel(practiceEntry)}).`; } if (target.dataset.key) { keyboardText += target.dataset.key.replace('◌', ''); render(); } if (target.dataset.backspace) { keyboardText = keyboardText.slice(0, -1); render(); } if (target.dataset.clearKeyboard) { keyboardText = ''; render(); } if (target.dataset.copyKeyboard) await navigator.clipboard?.writeText(keyboardText); if (target.dataset.copy) await navigator.clipboard?.writeText(target.dataset.copy); if (target.dataset.toggle && selected) { const current = state.review[selected.id] || emptyReview(); setState((old) => ({ ...old, review:{ ...old.review, [selected.id]:{ ...current, [target.dataset.toggle]:!current[target.dataset.toggle] } } })); } if (target.dataset.audio) { const entry = ipaEntries.find((item) => item.id === target.dataset.audio); const source = entry.audioSources.find((src) => src.kind === 'file' || src.kind === 'remote'); if (!source) { target.textContent = `⚠ ${t(lang(),'noAudio')}`; setTimeout(render, 2200); } else { const audio = new Audio(source.url); target.textContent = 'Loading…'; audio.addEventListener('canplay', () => { target.textContent = 'Playing…'; audio.play().catch(() => { target.textContent = 'Audio error'; }); }); audio.addEventListener('ended', render); audio.addEventListener('error', () => { target.textContent = 'Audio error'; }); } } if (target.dataset.finishOnboarding) setState({ ...state, onboarded:true, goal:document.querySelector('#goal').value, language:document.querySelector('#onboard-lang').value, level:document.querySelector('#level').value }); if (target.dataset.skipOnboarding) setState({ ...state, onboarded:true }); if (target.dataset.export) { const blob = new Blob([exportState(state)], { type:'application/json' }); const link = document.createElement('a'); link.href = URL.createObjectURL(blob); link.download = 'ipa-learner-progress.json'; link.click(); } if (target.dataset.reset && confirm('Reset local IPA progress?')) setState({ ...defaultState, onboarded:true, language:state.language }); });
chooseNextPractice();
render();
if ('serviceWorker' in navigator) window.addEventListener('load', () => navigator.serviceWorker.register('/public/sw.js').catch(() => undefined));
